# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Isuvgei950X4hhfDeUrXcrIhYQ4jTrBS
"""

import pandas as pd

# CSV faylni yuklash
url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"
df = pd.read_csv(url)


print(df.head())


df.rename(columns={
    'TotalCases': 'Jami_holatlar',
    'TotalDeaths': "Jami_o'limlar",
    'Country': 'Mamlakat',
    'date_reported': 'Sana_report',
}, inplace=True)

print("Yangi ustunlar nomi:", df.columns)


if 'Sana_report' in df.columns:
    df['Sana_report'] = pd.to_datetime(df['Sana_report'])
else:
    print("Ustun 'Sana_report' topilmadi. Ehtimol, ustun nomi boshqacha bo'lishi mumkin.")


def search_by_min_cases(min_holatlar):
    min_cases_data = df[df['Jami_holatlar'] <= min_holatlar]
    if not min_cases_data.empty:
        print(f"Kasallanishi {min_holatlar} dan kam bo'lgan davlatlar:")
        print(min_cases_data[['Mamlakat', 'Sana_report', 'Jami_holatlar', "Jami_o'limlar"]])
    else:
        print(f"Kasallanishi {min_holatlar} dan kam bo'lgan davlatlar topilmadi.")


def search_by_high_cases(yuqori_holatlar):
    high_cases_data = df[df['Jami_holatlar'] > yuqori_holatlar]
    if not high_cases_data.empty:
        print(f"Kasallanishi {yuqori_holatlar} dan yuqori bo'lgan davlatlar:")
        print(high_cases_data[['Mamlakat', 'Sana_report', 'Jami_holatlar', "Jami_o'limlar"]])
    else:
        print(f"Kasallanishi {yuqori_holatlar} dan yuqori bo'lgan davlatlar topilmadi.")


min_holatlar = int(input("Minimal kasallanish holatini kiriting (masalan, 10000): "))
search_by_min_cases(min_holatlar)


yuqori_holatlar = int(input("Yuqori kasallanish holatini kiriting (masalan, 100000): "))
search_by_high_cases(yuqori_holatlar)